//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface CreateArticleCommand {
    title?: string | undefined;
    message?: string | undefined;
    categoryId?: number;
    articleTags?: ArticleTagData[] | undefined;
}

export interface ArticleTagData {
    id?: number;
}

export interface ArticleDto {
    id?: number;
    title?: string | undefined;
    message?: string | undefined;
    categoryId?: number;
    category?: string | undefined;
    created?: Date;
    createdBy?: string | undefined;
    lastModified?: Date | undefined;
    articleTags?: ArticleTagsDto[] | undefined;
}

export interface ArticleTagsDto {
    id?: number;
    name?: string | undefined;
}

export interface ArticlesTitlesVm {
    articles?: ArticleTitleDto[] | undefined;
}

export interface ArticleTitleDto {
    title?: string | undefined;
    categoryId?: number;
}

export interface PaginatedListOfArticleDto {
    items?: ArticleDto[] | undefined;
    pageIndex?: number;
    totalPages?: number;
    totalCount?: number;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
}

export interface UpdateArticleCommand {
    id?: number;
    title?: string | undefined;
    message?: string | undefined;
    categoryId?: number;
    articleTags?: ArticleTagData2[] | undefined;
}

export interface ArticleTagData2 {
    id?: number;
}

export interface CreateCategoryCommand {
    name?: string | undefined;
}

export interface CategoriesVm {
    categories?: CategoryDto[] | undefined;
}

export interface CategoryDto {
    id?: number;
    name?: string | undefined;
}

export interface UpdateCategoryCommand {
    id?: number;
    name?: string | undefined;
}

export interface CreateTagCommand {
    name?: string | undefined;
    categoryId?: number;
}

export interface TagsVm {
    tags?: TagDto[] | undefined;
}

export interface TagDto {
    id?: number;
    name?: string | undefined;
    category?: string | undefined;
    categoryId?: number;
}

export interface TagsCategoryVm {
    tags?: TagCategoryDto[] | undefined;
}

export interface TagCategoryDto {
    id?: number;
    name?: string | undefined;
}

export interface UpdateTagCommand {
    id?: number;
    name?: string | undefined;
    categoryId?: number;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}